server.port=${PORT:8080}

spring.datasource.url=jdbc:mysql://monorail.proxy.rlwy.net:36380/railway?sslMode=REQUIRED
spring.datasource.username=root
spring.datasource.password=veAcAUSqiDZDYlSIxHMOvjVMLryeZvtG

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Serve frontend files directly from the frontend folder
spring.web.resources.static-locations=file:../frontend/

# Disable Thymeleaf (we use plain HTML + fetch API now)
spring.thymeleaf.enabled=false
